### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by vec123** [tilk/h264_image_transport#2]
Hi, I am having an issue when trying to build your package within a ROS-workspace. (h264_image_transport is a dependency for a tello_driver package).
The error goes like this:

src/h264_image_transport/src/manifest.cpp:4:24: 
error: expected constructor, destructor, or type conversion before ‘(’ token
 PLUGINLIB_DECLARE_CLASS(h264_image_transport, H264Subscriber, h264_image_transport::H264Subscriber, image_transport::SubscriberPlugin)

What is happening here? This seems to be code related, at least to me.... I am not too familiar with those things so maybe it's something on my side.
Any help would be appreciated.
Thanks a lot.

**Comment by tilk** [comment]
This package is, as you can probably see, unmaintained for quite some time; it was developed for ROS Kinetic, if I remember correctly. It's possible the reason for the error you see is that the current version of ROS changed something in plugin support. As I currently don't have time to support this package, I'll happily accept a pull request fixing this issue.

**Comment by ejalaa12** [comment]
@vec123 @tilk  I create a PR for this issue. Works on melodic :)
