### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by BrooklynBoy21** [tilk/h264_image_transport#4]
Sorry, there is no documentation and I want to ask how to use it.

I have built the pkg but when I launch the camera I didn't see any topic related to h264 like it is with theora for example.

Could you help?

**Comment by tilk** [comment]
This package provides only h264 decoding, no encoding. I used it to decode data encoded by hardware (by the Raspberry Pi GPU).

I shared the code as is, in hope it would be useful for someone who knows what he is doing. I wrote this years ago, don't use it anymore, and certainly don't provide support.
